# Setup
title: Xi Chen | 陈希
description: MS in Computer Science @ JHU | Machine Learning & Computer Vision Researcher
url: https://XiChen0522.github.io
avatar: /avatar.jpg # 请确保你的头像文件名为 avatar.jpg 并放在根目录或 assets 下
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems (保持不变)
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyll SEO Tag
twitter:
  username: XiChen0522 # 建议改为你的社交账号
  card: summary
logo: logo.png
social:
  name: Xi Chen
  links:
    - https://github.com/XiChen0522
    # - https://twitter.com/你的推特 (如果不常用可以删掉)

lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: Xi Chen
  url: https://github.com/XiChen0522
  email: xchen336@jh.edu
